
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true


  thymeleaf:
    prefix: classpath:templates/
    encoding: utf-8
    suffix: .html
    cache: false
    check-template: true
    enabled: true
  mvc:
    static-path-pattern: "/static/**"
  devtools:
    restart:
      enabled: false